azavea/ism-watershed-wellness-snapshot

scripts/lint
src/app/.prettierrc.json
src/app/package.json
src/app/src/App.js
src/app/src/App.test.js
src/app/src/index.js
src/app/src/reducers.js
src/app/src/serviceWorker.js
src/app/src/store.js
src/app/yarn.lock

Add Prettier to the project as well as a script to run ESLint from the command line.
While we have historically used ESLint for both code and style issues, [Prettier](https://prettier.io/) is used here to fix style issues. There is potential for conflict between the tools, and [libraries](https://github.com/prettier/eslint-config-prettier) to get around them. However, we are currently using the ESLint rules that come with CRA. The authors of CRA [decided to only have ESLint flag code issues](https://github.com/facebook/create-react-app/issues/808#issuecomment-279832535). They [recommend](https://github.com/facebook/create-react-app/issues/808#issuecomment-286870431) Prettier for code style. If we end up running into conflicts, we can add some further configuration.
Connects #8 
- On your …

Integrate Prettier

---

scripts/cibuild

Any errors or warnings will fail the build.
Connects to #14 
See build log at https://app.netlify.com/sites/ism-watershed-wellness-snapshot/deploys/5c1be03d9bb0870008680e3c
- View the build log for this PR on Netlify, and verify it failed because of lint.

Run eslint during CI build process

---

src/app/src/Map.js
src/app/src/Map.scss
src/app/src/map.reducers.js

Makes use of the style created by @alexelash, and matches the initial map view to that of the wireframes. Also makes the map not interactive (as designed) and adds the navigation control.
Connects #23
Wireframes:
Screenshot of app:
Follow-up: #25 
- Visit the app and verify the map looks roughly like the map in the wireframes. 
- Verify that the map is not interactive.

Implement custom map style and initial view

---

src/app/src/BackToMapButton.js
src/app/src/BackToMapButton.scss
src/app/src/Map.js
src/app/src/SensorMarker.js
src/app/src/index.js
src/app/src/map.actions.js
src/app/src/map.reducers.js
src/app/src/sensors.json

Adds markers for sensors to the map. Clicking a marker transitions the map to viewport centered around the marker in anticipation of the selected marker view. A "back to map" button is also added in this view.
Clicking it transitions the map back to the initial viewport.
Connects to #27
*Demo gif is low-res and short due to large file size.*
- Click a map marker. Verify the map zooms to that marker and that the "back to map" button appears.
- Click the "back to map" button. Verify the map returns to the initial position.

Add sensor markers and map interactions

---

src/app/src/Map.js

Utilize a version of the basemap that does not have the terrain/hillshade layer. This layer was causing the application to crash on iPads, which is the target device for this project. The crash seems to be caused by the issues described here: mapbox/mapbox-gl-js#4695
Connects #31 
- Visit the [deploy preview](https://deploy-preview-34--ism-watershed-wellness-snapshot.netlify.com/) site on an iPad.
- Click the sensor markers/back to map button, and verify the app doesn't crash after a few transitions.

Prevent app from crashing on iPad

---

src/app/package.json
src/app/yarn.lock

Upgrade to at least version 4.0.9, where the compass behavior has been fixed so that it is always pointing north.
Connects to #25
Compass is a little hard to see, and the pointer arrow is the darker of the two arrows.
**Before**
**After**
See https://github.com/uber/react-map-gl/pull/694 for more background.
- Run `./scripts/update` and then `./scripts/server`.
- Visit the app, and verify that the compass is now pointing north instead of in the direction of the map rotation.

Upgrade react-map-gl

---

README.md
scripts/analyze
src/app/package.json
src/app/yarn.lock

This tool will help us find sources of bloat in the app bundles.
Connects #36 
**Main bundle**
**Vendor bundle**
- Run `./scripts/update` to install the new dependency.
- From the `src/app` dir, run `npm run build` followed by `npm run analyze`.
- Verify the analyzer works and launches a web-based report.

Add bundle analyzer

---

src/app/src/Map.js

The style was exported from the previous account and is unmodified.
Connects #28
There is also now a API key specifically for the project, which can be retrieved by logging into the Azavea Mapbox account.
- Visit the site and ensure the basemap works as before.

Use basemap hosted on Azavea Mapbox account

---

src/app/src/Map.js

Conserves some screen space, which is especially helpful in the sensor overview view. Previously, the attribution was colliding with the MapBox logo when view on an iPad.
Connects #51
**Before**
**After**
The attribution and Mapbox logo are currently mispositioned when viewing in the browser.
- Ensure the attribution control is compact by default, and expands when hovered over.

Use compact attribution control

---

Vagrantfile
src/app/package.json
src/app/src/App.js
src/app/src/app.actions.js
src/app/src/app.reducers.js
src/app/src/constants.js
src/app/src/sensor.actions.js
src/app/src/sensorUtils.js
src/app/src/sensors.json
src/app/yarn.lock

The app markers will change their display depending on sensor data read regularly from real USGS sensors/data feeds. This app puts into place the initial work connecting the sensors to the app. Certainly more work will follow in terms of error handling, using back up data sources, persisting data, etc.
The requests to the 3 sensors are batch requested and handled at once. There's notably no error handling yet.
Sensors set to poll every 10 minutes, subj to change.
Connects #20
Sensors polling at 1 minute for testing:
I decided to try out `async/await`. I don't know that the implementation is more readable or effective than the standard request/then/catch promise workflow. Let me know your thoughts!
Also, I added changes to the Vagrantfile that helped my VM stop freezing -- it's the same …

Initial fetch and save sensor data

---

src/app/src/App.js
src/app/src/Map.js
src/app/src/SensorDetails.js
src/app/src/SensorMarker.js
src/app/src/SensorOverview.js
src/app/src/app.reducers.js
src/app/src/constants.js
src/app/src/map.reducers.js
src/app/src/sensorUtils.js

This sprint, we set up all the data needed for the front-end. This PR subs in dynamically generated data to the frontend, which previously showed static dummy data.
Connects #41
Connects #43 
(I accidentally did both)
You will see some TODOs. We will need some guidance from the client about how the variable score translates to qualitative buckets (positive, warning, and negative) given its range (i.e. 1-50NTU for Turbidity). For now, it was decided to just categorize scores as positive and negative if they are in or outside the range, respectively.
I was tempted to roll in #64, but am anticipating a fair amount of conflict rebasing on #63 already so I forewent that.
Netlify will suffice.

Wire up ratings and sensor data feed to frontend

---

src/app/src/App.js
src/app/src/Footer.js
src/app/src/__tests__/sensorutils.tests.js
src/app/src/constants.js
src/app/src/sensorUtils.js

The footer now displays a real value for time since last and latest data update. ~Time is displayed as days, hours, or minutes based on what seems sensible. I didn't consider the next jump up which is months, but I can add that 🤔Since sensors haven't been updating real-time as hoped for the app despite data being polled every 10 minutes, the timestamp is as of now kind of a let down 😢 ~
Edit: Display a time indicator that is appropriate for the time elapsed. The longer the time frame, the softer the messaging.
Connects #42
Using default data:
Using live sensor data:
~I was ambivalent between putting the logic in `App.js` vs `Footer.jsx`. I don't think it matters too much, however if you have a strong argument to move the logic to the Footer, I will consider.~ Moved to utils, makes sense …

Display dynamic timestamp in footer

---

src/app/package.json
src/app/src/Map.js
src/app/src/map.reducers.js
src/app/src/sass/05_base/_base.scss
src/app/src/sass/06_components/_map.scss
src/app/yarn.lock

This is a joint effort by @alexelash and I.
There are two main changes here to fix the issues described in #55:
- The height and width properties of the map component are removed from the redux state. Even though react-map-gl supports using strings to specify the map size (like `100%` or `100vw`), when we did use string values, they were overridden with the pixel values of the rendered map size. It is unclear why this was happening, however it was an easy change to remove these values from the state and specify them as props directly to the component.
- The CSS rules for the layout and map are revised to better support a full-screen map on the iPad.
Also, the react-map-gl library is updated in here in hopes that it would fix the issue. It didn't appear to help, but some bug fixes were …

Make map size dynamic and eliminate scrolling on iPad

---

src/app/src/Footer.js
src/app/src/SensorOverview.js
src/app/src/img/compass.svg
src/app/src/sass/06_components/_button-back.scss
src/app/src/sass/06_components/_map.scss
src/app/src/sensors.json

Following up #55, now that the map height is consistent across devices, the position of the map controls along the bottom of the map are adjusted. The controls are positioned so that they are above the footer on the overview map and along the bottom of the map when the sensor pane is open.
The sensor description text is also added here as it was a relatively simple, largely cosmetic change.
Connects #75 
Connects #83 
*Overview map*
*Map with sensor pane open*
- View the site in both a desktop browser and on an iPad, and verify the bottom map controls are also visible.

Adjust positioning of bottom map elements

---

src/app/src/sensorUtils.js

The provided format can be parsed in Chrome, but not Safari, which is the target device for the app.
The solution is from https://stackoverflow.com/a/5646753
Connects #84
- Visit the Delaware River sensor in both Chrome and Safari, and verify that the app works in both cases.

Reformat CSV timestamp to officially supported format

---

src/app/src/BackToMapButton.js
src/app/src/Intro.js
src/app/src/Map.js
src/app/src/constants.js
src/app/src/map.actions.js
src/app/src/map.reducers.js
src/app/src/sass/06_components/_map.scss
src/app/src/sass/07_layouts/_intro.scss

Implements a transition from the intro screen to the home screen, as shown in the prototype, via the following changes:
- The background fill on the intro screen was eliminated so that the map is visible.
- A new map style was created for the intro screen that does not have any labels. When transitioning, this style is swapped out for the style with the labels.
- The sensor markers are only added to the map after the "Find out" button is clicked.
- The map pitch is adjusted as the transition is happening.
Additionally, the style of the intro screen was adjusted to remove a "hiccup" when transitioning to the home screen style due to use of absolute positioning.
Connects #82 
Due to the map style, GIFs are very large and can't be uploaded to Github. Check out the Netlify deploy preview.
- …

Implement intro screen transition

---

src/app/src/app.actions.js
src/app/src/constants.js
src/app/src/sensorUtils.js
src/app/src/sensors.json

Updates the sensor healthy ranges based on feedback from the client, add fallback to sensor defaults in case of polling error, and add the "fair" calculation to the sensor overall rating logic.
See commit messages for details.
Connects #79 
Connects #69 
- Load the app, visit a sensor, and open the sensor detail modal. 
- Verify the fish symbol for each variable is correct given the variable value and healthy range (outside of range = red, within 10% of edges = yellow, everything else = blue).
- Also verify that for the two failing sensors (Tinicum and Wissahickon), the default data is used.

Make various sensor related updates

---

src/app/src/sass/06_components/_modal.scss

This ended up being a quick fix—our modals were `position: absolute;` and needed to be `position: relative;` to have a scrollable height. Why did it ever work on iPads? Good question.
Connects #90
Safari
Firefox
The fish don't look centered on the Browserstack iPad but do on desktop—I didn't attempt to fix in this issue, since I figure there will be a polish round later.
* `git pull` 
* Enter app, open a site, click the little chart icon in the sidebar
* attempt to scroll
* Ideally try this on an iPad (I used Browserstack, both chrome and safari)

Fix broken scroll

---

src/app/src/constants.js

The previous date caused the API to return a 403. It is not clear why, but having a more recent date does not cause the same issue.
Connects #103 
This is considered a quick fix to get live data back in the app. Budget permitting, we may need a more dynamic way to detect that last live date. See https://github.com/azavea/ism-watershed-wellness-snapshot/issues/68
- Verify all of the sensor API requests succeed and the sensor data is from today.

Update last live date

---

src/app/src/sensorUtils.js
src/app/src/sensors.json

The healthy ranges were provided in Fahrenheit, but the sensor data is provided in Celsius. Convert to Fahrenheit for calculation and display purposes in the app.
Also, at the moment, we only have 4 variables per sensor instead of 5. The overall rating calculation was designed for 5 variables. Modify it for 4 until IBI is added.
Connects #109 
- Visit the sensors, and verify the temperature is displayed in Fahrenheit, and that the temperature healthy range calculation is resulting in the correct fish color.

Convert Celsius to Fahrenheit 

---

src/app/src/sass/01_settings/_type.scss

We were linking to a font hosted on Azavea's account. This PR adds in the client's embed link.
Connects #32
I turned off the downloaded versions of the font on my machine and it seemed to work... but we should definitely make sure it works on Netlify and someone else's computer. 
* `git pull`
* View the website and ensure that fonts look right (feel free to send me a screenshot so I can confirm)

Add in client Typekit embed link

---

src/app/src/constants.js
src/app/src/sensorUtils.js

Updates the variable descriptions based on input from the client. Also changes the way "fair" is calculated for turbidity per the client.
Connects #116 
**Turbidity rating**
Before:
After:
- Open one of the sensor panels, and verify the text matches what was provided by the client.
- Open the Wissahickon panel, and verify the Turbidity value, which is currently 0, is consider good and not fair even though it's at the bottom end of the healthy range.

Text and turbidity rating changes

---

src/app/src/constants.js
src/app/src/sensorUtils.js

We were seeing failing requests (`403` error code) to the waterservices API. Upon investigation of USGS documentation, local testing, and talking with IT at USGS, we now know that requests for data from the waterservices API older than 120 days should be requested from the url prefixed 'nwis'. Otherwise, the request gets redirected to a different origin (waterservices to nwis.waterservices) and the app encounters CORS issues in the browser. The CORS failure is sneakily masquerading as the `403`.
In discussion with USGS, we clarified some other details that I'll note here:
- There is no rate limiting on these endpoints
- There is no combination of params to pull most recent data
We'd have to provide some time band through `startDate`, `period` and/or `modifiedSince`. `modifiedSince` looks …

Use special endpoint for waterservices data > 120 days
